/**
 * One-shot build-time asset pipeline. Runs before `vite dev` and `vite build`
 * (see package.json). Every step is best-effort: a failure logs a warning and
 * the build continues — the site degrades to the original single-size image or
 * an omitted <lastmod>, never a broken build.
 *
 *   1. Open Graph card            -> public/og-image.jpg
 *   2. Responsive photo variants  -> public/img/<name>-{640,960,1280}.webp
 *   3. Multi-res favicon          -> public/favicon.ico  (PNG-in-ICO)
 *   4. Per-route git commit dates -> src/generated/route-meta.ts
 */
import { execFileSync } from "node:child_process";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { mkdirSync, writeFileSync, readFileSync, existsSync } from "node:fs";

import sharp from "sharp";

import { generateOgImage } from "./generate-og-image.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const rel = (...p) => resolve(root, ...p);

const step = async (label, fn) => {
  try {
    await fn();
    console.log(`  ok   ${label}`);
  } catch (err) {
    console.warn(`  warn ${label} skipped: ${err?.message ?? err}`);
  }
};

/* 1 — Open Graph card ----------------------------------------------------- */
await step("og-image", () => generateOgImage());

/* 2 — Responsive photo variants ---------------------------------------------
 * The four hero photos ship at 1600x1000. Phones were downloading all of it;
 * these widths + a `sizes` hint on each <img> cut the mobile payload ~70%.  */
const PHOTOS = ["hero-spain", "madrid", "barcelona-interior", "costa-blanca"];
const WIDTHS = [640, 960, 1280];
await step("responsive images", async () => {
  const outDir = rel("public/img");
  mkdirSync(outDir, { recursive: true });
  for (const name of PHOTOS) {
    const src = rel("src/assets", `${name}.webp`);
    if (!existsSync(src)) {
      console.warn(`       (no source for ${name})`);
      continue;
    }
    for (const w of WIDTHS) {
      await sharp(src)
        .resize(w, null, { withoutEnlargement: true })
        .webp({ quality: 78, effort: 5 })
        .toFile(resolve(outDir, `${name}-${w}.webp`));
    }
  }
});

/* 3 — favicon.ico ---------------------------------------------------------------
 * Old clients and some crawlers still hit /favicon.ico blindly. The ICO
 * container format permits a raw PNG payload, so we wrap the existing 32px
 * PNG rather than pulling in an ico encoder.                                  */
await step("favicon.ico", () => {
  const png = readFileSync(rel("public/favicon-32.png"));
  const header = Buffer.alloc(6);
  header.writeUInt16LE(0, 0); // reserved
  header.writeUInt16LE(1, 2); // type: icon
  header.writeUInt16LE(1, 4); // image count
  const entry = Buffer.alloc(16);
  entry.writeUInt8(32, 0); // width  (0 => 256, 32 fits)
  entry.writeUInt8(32, 1); // height
  entry.writeUInt8(0, 2); // palette
  entry.writeUInt8(0, 3); // reserved
  entry.writeUInt16LE(1, 4); // colour planes
  entry.writeUInt16LE(32, 6); // bits per pixel
  entry.writeUInt32LE(png.length, 8); // payload size
  entry.writeUInt32LE(6 + 16, 12); // payload offset
  writeFileSync(rel("public/favicon.ico"), Buffer.concat([header, entry, png]));
});

/* 4 — per-route git commit dates ---------------------------------------------
 * Honest <lastmod> for the sitemap: the day each route's source last changed,
 * not "today" on every deploy. Falls back to an empty map on a shallow clone
 * or outside git, and the sitemap then omits <lastmod> entirely.             */
await step("route-meta", () => {
  const ROUTES = {
    "/": "src/routes/index.tsx",
    "/why-spain": "src/routes/why-spain.tsx",
    "/services": "src/routes/services.tsx",
    "/opportunities": "src/routes/opportunities.tsx",
    "/about": "src/routes/about.tsx",
    "/contact": "src/routes/contact.tsx",
  };
  const lastmod = {};
  for (const [path, file] of Object.entries(ROUTES)) {
    try {
      const iso = execFileSync("git", ["log", "-1", "--format=%cs", "--", file], {
        cwd: root,
        encoding: "utf8",
        stdio: ["ignore", "pipe", "ignore"],
      }).trim();
      if (/^\d{4}-\d{2}-\d{2}$/.test(iso)) lastmod[path] = iso;
    } catch {
      /* shallow clone / not a git checkout — leave this route without a date */
    }
  }
  const outDir = rel("src/generated");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    resolve(outDir, "route-meta.ts"),
    `// Generated by scripts/build-assets.mjs — do not edit.\n` +
      `export const ROUTE_LASTMOD: Record<string, string> = ${JSON.stringify(lastmod, null, 2)};\n`,
  );
});

console.log("build-assets: done");
